# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Author

# Model Form Field configuration
form: $/queni/dlearning/models/authors/fields.yaml

# Model Class name
modelClass: Queni\DLearning\Models\Authors

# Default redirect location
defaultRedirect: queni/dlearning/authors

# Create page
create:
    title: Create Author
    redirect: queni/dlearning/authors/update/:id
    redirectClose: queni/dlearning/authors

# Update page
update:
    title: Edit Author
    redirect: queni/dlearning/authors
    redirectClose: queni/dlearning/authors

# Preview page
preview:
    title: Preview Author