# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/queni/dlearning/models/categories/fields.yaml

# Model Class name
modelClass: Queni\DLearning\Models\Categories

# Default redirect location
defaultRedirect: queni/dlearning/categories

# Create page
create:
    title: Create Category
    redirect: queni/dlearning/categories/update/:id
    redirectClose: queni/dlearning/categories

# Update page
update:
    title: Edit Category
    redirect: queni/dlearning/categories
    redirectClose: queni/dlearning/categories

# Preview page
preview:
    title: Preview Category