# ===================================
#  Relation Behavior Config
# ===================================

users:
    label: пользователя
    list: $/queni/dlearning/models/availablescourses/columns_relation.yaml
    view:
        toolbarButtons: add|remove
